add linear regression files
quaterhalfbro/ML_sect_tasks pull request #2
Opened 2021-11-01 13:08 UTC by quaterhalfbro

2021-11-07 20:35 UTC, ARQtty requested changes
добавить типы и выделить рансак регрессию в отдельный объект

2021-11-07 20:35 UTC, ARQtty commented on LinearRegression.py
> +    def fit(self, x: np.array, y: np.array, l2_regulation=0):
np.ndarray - это тип, а np.array - это функция

2021-11-07 20:35 UTC, ARQtty commented on LinearRegression.py
> +    def fit(self, x: np.array, y: np.array, l2_regulation=0):
+ обучение не должно возвращать меру качества. Обучение - учит. И только

2021-11-07 20:35 UTC, ARQtty commented on LinearRegression.py
> +    '''def gradient_fit(self, x: np.array, y: np.array, learning_rate, epochs_count):
комментить лучше с помощью #

2021-11-07 20:35 UTC, ARQtty commented on LinearRegression.py
> +    def predict(self, x: np.array):
нет возвращаемого типа

2021-11-07 20:35 UTC, ARQtty commented on LinearRegression.py
> +    def r(self, x: np.array, y: np.array):
нет возвращаемого типа

2021-11-07 20:35 UTC, ARQtty commented on LinearRegression.py
> +    def score(self, x: np.array, y: np.array):
нет возвращаемого типа

2021-11-07 20:35 UTC, ARQtty commented on LinearRegression.py
> +    def r(self, x: np.array, y: np.array):
имя r не очень трактуемое. Стоит изменить

2021-11-07 20:35 UTC, ARQtty commented on LinearRegression.py
> +    def cross_val_score(self, x: np.array, y: np.array, cv=5):
нет возвращаемого типа, нет типа у переменной cv

2021-11-07 20:35 UTC, ARQtty commented on LinearRegression.py
> +    def ransac_fit(self, x: np.array, y: np.array, radius=1):
это лучше сделать в отдельном классе. Рансак регрессия - это не Linear Regression, ей тут не место

2021-11-07 20:35 UTC, ARQtty commented on LinearRegression.py
> +    def ransac_fit(self, x: np.array, y: np.array, radius=1):
если уж делать новые классы, то стоит озаботиться наследованием и выделением общего кода

2021-11-12 21:53 UTC, ARQtty requested changes
Напутал в ООП. Надо сделать красиво

2021-11-12 21:53 UTC, ARQtty commented on LinearRegression.py
> +        except np.linalg.LinAlgError:
не стоит возвращать -1. Непонятно что с этим делать. И пользователь не узнаёт об ошибке. Лучше чтобы программа падала в случае невозможности построить модель

2021-11-12 21:53 UTC, ARQtty commented on LinearRegression.py
> +        return score, points
fit должен обучать модель. Скоринг в его задачи не входит

2021-11-12 21:53 UTC, ARQtty commented on LinearRegression.py
> +        return 0
у классов линрег и рансак разные возвращаемые значения. Это совсем не дело. Сделай общий интерфейс для них. В нём создай абстрактный метод fit. Реализуй интерфейс отдельно каждым классом

2021-11-13 16:29 UTC, ARQtty commented on LinearRegression.py
> +class RansacRegression(LinearRegression):
1 класс - 1 файл

2021-11-14 08:02 UTC, quaterhalfbro commented on LinearRegression.py
> +class RansacRegression(LinearRegression):
А можно разве наследовать класс от класса, который в другом файле?

2021-11-14 08:05 UTC, quaterhalfbro commented on LinearRegression.py
> +class RansacRegression(LinearRegression):
А, все сорян, вопрос закрыт

2021-11-18 13:54 UTC, ARQtty reviewed
поменяй имена файлов и будет гуд

2021-11-18 13:54 UTC, ARQtty commented on LinearRegression/LinearRegression.py
> +import numpy as np
файлы именуются в snake_case. Классы именуются в CamelCase. В данном случае надо назвать файл linear_regression.py

Модули тоже следуюет именовать в snake_case

2021-11-18 13:54 UTC, ARQtty commented on LinearRegression/LinearRegression.py
> +    def predict(self, x: np.array) -> np.ndarray:
ndarray

2021-11-18 13:54 UTC, ARQtty commented on LinearRegression/LinearRegression.py
> +    def square_error(self, x: np.array, y: np.array) -> float:
ndarray

2021-11-18 13:54 UTC, ARQtty commented on LinearRegression/LinearRegression.py
> +    def square_error(self, x: np.array, y: np.array) -> float:
и далее тоже

2021-11-21 11:04 UTC, ARQtty approved these changes

2021-11-21 12:09 UTC, merged